# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Perlbal-XS-HTTPHeaders
version:      0.18
version_from: lib/Perlbal/XS/HTTPHeaders.pm
installdirs:  site
requires:
    Perlbal:                       0
    Perlbal::HTTPHeaders:          0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
